resources:
  - name: mynpm_project
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_builds

  - name: mymvn
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/j-sample-node 
      
      
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: mynpm-testing

pipelines:
  - name: npm_pipeline
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: bindu_mvn_local
          sourceLocation: .
          inputResources:
            - name: mymvn
          integrations:
            - name: bindu_arti
#         execution:
#           onStart:
#             - ls -la
#             - pushd $res_mynpm_project_resourcePath    
            
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: bindu_mvn_local
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
          outputResources:
            - name: npm_build_info
          integrations:
            - name: bindu_arti
