resources:
  - name: mynpm_project
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_builds

  - name: mymvn
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/j-sample-node 
      
      
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: mynpm-testing

  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: npmbuild-testing
      
  - name: npm_releaseBundle 
    type: ReleaseBundle
    configuration:
      sourceArtifactory: bindu_arti
      name: bindu_mvn_local
      version: v1.1.1
      isSigned: false 
      
  - name: npm_signedBundle
    type: ReleaseBundle
    configuration:
      sourceArtifactory: bindu_arti
      name: npmsign
      version: v1.0.1
      isSigned: true       

pipelines:
  - name: npm_pipeline
    steps:
      - name: npm_Build
        type: NpmBuild
        configuration:
          repositoryName: bindu_mvn_local
          sourceLocation: .
          inputResources:
            - name: mymvn
          integrations:
            - name: bindu_arti
        execution:
          onStart:
            - ls -la
#             - pushd $res_mynpm_project_resourcePath    
            
      - name: npm_Pub
        type: NpmPublish
        configuration:
          repositoryName: bindu_mvn_local
          autoPublishBuildInfo: true
          inputSteps:
            - name: npm_Build
          outputResources:
            - name: npm_build_info
          integrations:
            - name: bindu_arti
            
      - name: npm_Promote
        type: PromoteBuild
        configuration:
          targetRepository: bindu_mvn_local
          inputResources:
            - name: npm_build_info
          outputResources:
            - name: npm_build_promote 
            
            
      - name: npm_Bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: bundle_release_exp
          releaseBundleVersion: 1.0.2
          dryRun: true
          sign: true
          releaseNotes:         
            content: bundle_npm 
            syntax:  plain_text 
          inputResources:
            - name: npm_build_promote 
          outputResources:
            - name: npm_releaseBundle    
            
      - name: npm_SignBundle
        type: SignReleaseBundle
        configuration: 
          inputResources:
            - name: npm_releaseBundle  # one ReleaseBundle is mandatory
              #trigger: false    # default true
          outputResources:
            - name: npm_signedBundle    # ReleaseBundle resource         
