resources:
  - name: mynpm_project
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_builds

  - name: mymvn
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/j-sample-node 
      
      
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: mynpm-testing

  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: npmbuild-testing

pipelines:
  - name: npm_pipeline
    steps:
      - name: npm_Build
        type: NpmBuild
        configuration:
          repositoryName: bindu_mvn_local
          sourceLocation: .
          inputResources:
            - name: mymvn
          integrations:
            - name: bindu_arti
#         execution:
#           onStart:
#             - ls -la
#             - pushd $res_mynpm_project_resourcePath    
            
      - name: npm_Pub
        type: NpmPublish
        configuration:
          repositoryName: bindu_mvn_local
          autoPublishBuildInfo: true
          inputSteps:
            - name: npm_Build
          outputResources:
            - name: npm_build_info
          integrations:
            - name: bindu_arti
            
      - name: npm_Promote
        type: PromoteBuild
        configuration:
          targetRepository: bindu_mvn_local
          inputResources:
            - name: npm_build_info
          outputResources:
            - name: npm_build_promote         
