resources:
  - name: mymvn_project
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/project-examples
      sha: mvnbuild
      
  - name: mvn_Buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: mvntest

pipelines:
  - name: pipeline_mvn
    steps:
      - name: mvnBuild_1
        type: MvnBuild
        configuration:
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: mymvn_project
          integrations:
            - name: bindu_arti
            - name: bindu_slack
#           runtime:            
#             type: image
#             image:
#               custom:
#                 name: drydock/u16java
#                 tag: master
#                 options: ""
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - send_notifications bindu_slack

      - name: mvnpublish
        type: PublishBuildInfo
        configuration:
          integrations:
            - name: bindu_slack
          inputSteps:
            - name: mvnBuild_1
          outputResources:
            - name: mvn_Buildinfo
        execution:
          onSuccess:
            - send_notifications bindu_slack
