resources:
  - name: dockerbuild_Repo
    type: GitRepo
    configuration:
      path: bindushree16/test_builds
      gitProvider: bindu_github
      buildOn:
         commit: false 

pipeline: 
  - name: pipee1
    steps:
      - name: test_steps_1
        type: DockerBuild
        configuration:
          # for docker:
          dockerFileLocation: . # required
          dockerFileName: Dockerfile     # required
          dockerImageName: 34.66.110.173:8081/bindu_test/myimg # required 
          dockerImageTag: latest    # required
          inputResources:
#             - artifactoryFileSpec      # optional
            - dockerbuild_Repo     # required
#             - my_docker_image      # optional if base image is private
