resources:
  - name: dockerbuild_test
    type: GitRepo
    configuration:
      path: bindushree16/test_builds
      gitProvider: bindu_github
#       branches:
#         include: dockerbuild
      buildOn:
         commit: false
      sha: dockerbuild  
      
  - name: docker_Buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: dockertest    


pipelines: 
  - name: pipee1
    steps:
      - name: test_dockerBuild
        type: DockerBuild
        configuration:
#           nodePool: tr_u16
          # for docker:
          dockerFileLocation: . # required
          dockerFileName: Dockerfile     # required
          dockerImageName: 34.66.110.173:8081/bindu_local/bindu  # required 
          dockerImageTag: myimage_$pipeline_name.$run_number   # required
          integrations:
            - name: bindu_arti
          inputResources:
            - name: dockerbuild_test    # required
#             - artifactoryFileSpec      # optional
#             - my_docker_image      # optional if base image is private
        execution:
          onStart:
            - docker images 
            - printenv
            - ls -la
            - pushd $res_dockerbuild_test_resourcePath
            - ls -la
          onSuccess:
            - docker images  

      - name: test_dockerPush
        type: DockerPush
        configuration:
#           nodePool: tr_u16
          targetRepository: bindu_local  #required
          integrations:
            - name: bindu_arti     # required
          inputSteps:
            - name: test_dockerBuild     # required
#           outputResources:
#             - name: docker_Buildinfo      # required if autoPublishBuildInfo is true 
            
      - name: test_dockerpublish
        type: PublishBuildInfo
        configuration:
          #inherits from bash
#           integrations:
#             - name: bindu_arti     # required
          inputSteps:
            - name: test_dockerBuild  #test_dockerPush     # required
          outputResources:
            - name: docker_Buildinfo       
            
    
 
