resources:
  - name: dockerbuild_test
    type: GitRepo
    configuration:
      path: bindushree16/test_builds
      gitProvider: bindu_github
#       branches:
#         include: dockerbuild
      buildOn:
         commit: false
      sha: dockerbuild   


pipelines: 
  - name: pipee1
    steps:
      - name: test_dockerBuild
        type: DockerBuild
        configuration:
          # for docker:
          dockerFileLocation: . # required
          dockerFileName: Dockerfile     # required
          dockerImageName: 34.66.110.173:8081/bindu_test/ubuntuimag # required 
          dockerImageTag: latest    # required
          integrations:
            - name: bindu_arti
          inputResources:
            - name: dockerbuild_test    # required
#             - artifactoryFileSpec      # optional
#             - my_docker_image      # optional if base image is private
        execution:
          onStart:
            - docker images 
            - printenv
            - ls -la
            - pushd $res_dockerbuild_test_resourcePath
            - ls -la
          onSuccess:
            - docker images   
            
    
 
