resources:
  - name: mynpm_project
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/test_builds
      sha: npmbuild
      
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bindu_arti
      buildNumber: 1
      buildName: mynpm-testing

pipelines:
  - name: npm_pipeline
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: bindu_test
          sourceLocation: .
          inputResources:
            - name: mynpm_project
          integrations:
            - name: bindu_arti
            
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: bindu_test
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
          outputResources:
            - name: npm_build_info
          integrations:
            - name: bindu_arti
